FROM node:20-alpine AS build
ARG REACT_APP_API_URL=http://138.197.202.120:5000
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
ENV REACT_APP_API_URL=$REACT_APP_API_URL
RUN npm run build
 
FROM nginx:alpine
COPY --from=build /app/build /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
